# Configuration for Weather API
weather-api/mp-rest/url=https://api.open-meteo.com
weather-api/mp-rest/scope=jakarta.enterprise.context.ApplicationScoped

# TODO: TASK 4 - Configure the MCP Server URL here
mcp-api/mp-rest/url=https://postman-echo.com
mcp-api/mp-rest/scope=jakarta.enterprise.context.ApplicationScoped

# Plagiarism detection "Salt" - do not change
assignment.fingerprint=7b3a4f12
